<nav class="navbar bg-dark sticky-top text-white">
    <div class="container">
    <div class="m-2">
        <i class="bi bi-key"></i>
    </div>
    <div>
        <h2>Admin Interface</h2>
    </div>
    <div>
        <a class="m-2 text-white" href="/logout.php">
            ADMIN <i class="bi bi-person"></i>
        </a>
    </div>
    <div class="container">
        <ul class="nav text-white">
            <li class="nav-item"> <a class='nav-link' href='./users.php'>Users</a></li>
            <li class="nav-item"> <a class='nav-link' href='./groups.php'>Groups</a></li>
            <li class="nav-item"> <a class='nav-link' href='./vpns.php'>VPNs</a></li>
            <li class="nav-item"> <a class='nav-link' href='./credentials.php'>Credentials</a></li>
        </ul>
    </div>
</nav>